# Generated by Django 5.2.3 on 2025-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='languague',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='es', max_length=255),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=255),
        ),
    ]
